version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      target: development
    container_name: healthassist-api
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/healthassistpro
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - healthassist-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: healthassist-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - healthassist-network

  # MongoDB service
  mongodb:
    image: mongo:4.4
    container_name: healthassist-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthassist-network

  # MongoDB Express (Admin Interface)
  mongo-express:
    image: mongo-express
    container_name: healthassist-db-admin
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - healthassist-network

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:

networks:
  healthassist-network:
    driver: bridge 